version: '3'
services:
 
  companies:
    build: './companies'
    ports:
      - "5001:5000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/Business

  workspaces:
    build: './workspaces'
    ports:
      - "5002:5000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/Business

  users:
    build: './users'
    ports:
      - "5003:5000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/Business
  
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - companies
      - workspaces
      - users