version: '2'
services:
 
  companies:
    build: './companies'
    command: npm run test
    ports:
      - "5001:5000"
    links:
      - db:mongodb  
    volumes:
      # - /app/node_modules
      - .:/app  
    restart: on-failure  
    depends_on: 
      - db
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/Business  
      - MONGOTESTURL=mongodb://mongodb:27017/Business-test  

    

  workspaces:
    build: './workspaces'
    command: npm run test
    ports:
      - "5002:5000"
    links:
      - db:mongodb  
    volumes:
      # - /app/node_modules
      - .:/app  
    restart: on-failure   
    depends_on: 
      - db
      - companies
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/Business  
      - MONGOTESTURL=mongodb://mongodb:27017/Business-test  
    

  users:
    build: './users'
    command: npm run test
    ports:
      - "5003:5000"
    links:
      - db:mongodb  
    volumes:
      # - /app/node_modules
      - .:/app  
    restart: on-failure  
    depends_on: 
      - db
      - workspaces
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongodb:27017/Business  
      - MONGOTESTURL=mongodb://mongodb:27017/Business-test 

  
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - companies
      - workspaces
      - users